name: Publish Document to Release

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    name: Publish Document to Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Install Pandoc, LaTeX, xelatex, and Liberation fonts
      - name: Setup Pandoc, LaTeX, xelatex, and Liberation fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-xetex
          # Install Liberation fonts
          sudo apt-get install -y fonts-liberation
          
      # Convert Markdown files to PDFs using Liberation Serif as the font
      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdfs
          for file in charta/*.md house-rules/*.md statutes/*.md; do
            pandoc "$file" -o "pdfs/$(basename "${file%.*}").pdf" --pdf-engine=xelatex -V mainfont="Liberation Serif"
          done
      
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Get Release
        id: release
        uses: bruceadams/get-release@v1.2.0
      
      # Upload each PDF as a separate release asset
      - name: Attach PDFs to Release
        run: |
          for pdf in pdfs/*.pdf; do
            echo "Uploading $(basename "$pdf")"
            gh release upload ${{ github.ref_name }} "$pdf" --clobber --token ${{ secrets.GITHUB_TOKEN }}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

