name: Convert Markdown to PDF

on:
  release:
    types: [created]
jobs:
  convert-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Setup Pandoc
      run: |
        sudo apt update
        sudo apt install -y pandoc

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh

    - name: Convert and Upload
      run: |
        for dir in charta statutes house-rules; do
          mkdir -p "pdf/$dir"
          for file in $(find $dir -name '*.md'); do
            pdf="pdf/${file%.md}.pdf"
            pandoc "$file" -o "$pdf"
            gh release upload ${{ github.ref_name }} "$pdf" --clobber
          done
        done
