name: Publish Document to Release

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  converttopdf:
      name: Build PDF
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: Build PDFs
          run: |-
            npm install -g md-to-pdf
            mkdir -p pdfs
            echo; echo "Generating Statutes"
            cat statutes/Vereinsstatuten.md | md-to-pdf > pdfs/vereinsstatuten.pdf
            echo; echo "Generating Charta"
            cat charta/Charta.md | md-to-pdf > pdfs/charta.pdf
            echo; echo "Generating houserules"
            cat house-rules/houserules.md | md-to-pdf > pdfs/houserules.pdf
    
        - name: Attach Files to Release
          run: |
            for pdf in pdfs/*.pdf; do
              echo "Uploading $(basename "$pdf")"
              gh release upload ${{ github.ref_name }} "$pdf" --clobber
            done


