name: Publish Document to Release

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    name: Publish Document to Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Install Pandoc, LaTeX, and xelatex
      - name: Setup Pandoc, LaTeX, and xelatex
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          # Install the full TeX Live package to ensure xelatex is included
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-xetex
          
      # Convert Markdown files to PDFs using a readable font
      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdfs
          for file in charta/*.md house-rules/*.md statutes/*.md; do
            pandoc "$file" -o "pdfs/$(basename "${file%.*}").pdf" --pdf-engine=xelatex -V mainfont="Times New Roman"
          done
      
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Get Release
        id: release
        uses: bruceadams/get-release@v1.2.0
      
      # Upload each PDF as a separate release asset
      - name: Attach PDFs to Release
        run: |
          for pdf in pdfs/*.pdf; do
            asset_name=$(basename "$pdf")
            echo "Uploading $asset_name"
            gh release upload ${{ github.ref }} "$pdf" --name "$asset_name" --token ${{ secrets.GITHUB_TOKEN }}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
