name: Publish Document to Release

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        name: "Generating Statutes"
        with:
          input_dir: statutes
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false

      - name: Attach Statutes to Release
        run: |
          for pdf in pdfs/*.pdf; do
            echo "Uploading $(basename "$pdf")"
            gh release upload ${{ github.ref_name }} "$pdf" --clobber
          done

      - uses: baileyjm02/markdown-to-pdf@v1
        name: "Generating Charta"
        with:
          input_dir: charta
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false

      - name: Attach Charta to Release
        run: |
          for pdf in pdfs/*.pdf; do
            echo "Uploading $(basename "$pdf")"
            gh release upload ${{ github.ref_name }} "$pdf" --clobber
          done

      - uses: baileyjm02/markdown-to-pdf@v1
        name: "Generating House-Rules"
        with:
          input_dir: house-rules
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false
      
      - name: Attach House-Rules to Release
        run: |
          for pdf in pdfs/*.pdf; do
            echo "Uploading $(basename "$pdf")"
            gh release upload ${{ github.ref_name }} "$pdf" --clobber
          done


